'use client';

import { useState } from 'react';

interface GlossaryTerm {
  term: string;
  definition: string;
  category: 'fundamental' | 'valuation' | 'technical' | 'general';
}

const glossaryTerms: GlossaryTerm[] = [
  // Fundamental Analysis Terms
  {
    term: 'Revenue Growth',
    definition: 'The percentage increase in a company\'s sales over a specific period, typically measured year-over-year. Higher revenue growth indicates expanding business operations.',
    category: 'fundamental'
  },
  {
    term: 'Earnings Growth',
    definition: 'The rate at which a company\'s earnings per share (EPS) increases over time. Strong earnings growth suggests improving profitability.',
    category: 'fundamental'
  },
  {
    term: 'Profit Margin',
    definition: 'The percentage of revenue that remains as profit after all expenses. Calculated as Net Income / Revenue. Higher margins indicate better operational efficiency.',
    category: 'fundamental'
  },
  {
    term: 'Debt-to-Equity Ratio',
    definition: 'A measure of financial leverage calculated as Total Debt / Shareholder Equity. Lower ratios generally indicate less financial risk.',
    category: 'fundamental'
  },
  {
    term: 'Free Cash Flow',
    definition: 'Cash generated by operations minus capital expenditures. Represents cash available for dividends, debt repayment, or reinvestment.',
    category: 'fundamental'
  },
  
  // Valuation Terms
  {
    term: 'P/E Ratio',
    definition: 'Price-to-Earnings ratio. Calculated as Stock Price / Earnings Per Share. Indicates how much investors are willing to pay per dollar of earnings.',
    category: 'valuation'
  },
  {
    term: 'P/B Ratio',
    definition: 'Price-to-Book ratio. Calculated as Stock Price / Book Value Per Share. Compares market value to accounting book value.',
    category: 'valuation'
  },
  {
    term: 'Fair Value',
    definition: 'An estimate of a stock\'s intrinsic worth based on fundamental analysis. Used to determine if a stock is overvalued or undervalued.',
    category: 'valuation'
  },
  {
    term: 'Peer Comparison',
    definition: 'Analyzing a company\'s valuation metrics relative to similar companies in the same industry to assess relative value.',
    category: 'valuation'
  },
  
  // Technical Analysis Terms
  {
    term: 'Moving Average',
    definition: 'The average price of a stock over a specific time period. Used to identify trends and potential support/resistance levels.',
    category: 'technical'
  },
  {
    term: 'RSI',
    definition: 'Relative Strength Index. A momentum indicator ranging from 0-100. Values above 70 suggest overbought conditions, below 30 suggest oversold.',
    category: 'technical'
  },
  {
    term: 'Trend',
    definition: 'The general direction of a stock\'s price movement over time. Can be upward (bullish), downward (bearish), or sideways (neutral).',
    category: 'technical'
  },
  {
    term: 'Moving Average Crossover',
    definition: 'When a short-term moving average crosses above or below a long-term moving average, potentially signaling a trend change.',
    category: 'technical'
  },
  
  // General Investment Terms
  {
    term: 'Economic Moat',
    definition: 'Sustainable competitive advantages that protect a company from competitors, such as patents, brand strength, or cost leadership.',
    category: 'general'
  },
  {
    term: 'Market Capitalization',
    definition: 'The total market value of a company\'s outstanding shares. Calculated as Share Price × Total Shares Outstanding.',
    category: 'general'
  },
  {
    term: 'Dividend Yield',
    definition: 'Annual dividend payment divided by stock price, expressed as a percentage. Indicates income return on investment.',
    category: 'general'
  },
  {
    term: 'Risk Tolerance',
    definition: 'An investor\'s ability and willingness to endure market volatility and potential losses in pursuit of investment returns.',
    category: 'general'
  },
  {
    term: 'Investment Horizon',
    definition: 'The length of time an investor expects to hold an investment before needing the funds. Longer horizons typically allow for more risk.',
    category: 'general'
  },
  {
    term: 'Position Sizing',
    definition: 'Determining the appropriate amount of capital to allocate to each investment based on risk tolerance and portfolio strategy.',
    category: 'general'
  },
  {
    term: 'Analyst Consensus',
    definition: 'The aggregate recommendation from professional analysts, typically expressed as Strong Buy, Buy, Hold, Sell, or Strong Sell.',
    category: 'general'
  },
  {
    term: 'Price Target',
    definition: 'An analyst\'s projection of where a stock\'s price will be in the future, typically 12 months ahead.',
    category: 'general'
  }
];

export default function Glossary() {
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [searchTerm, setSearchTerm] = useState('');

  const categories = [
    { id: 'all', label: 'All Terms', icon: '📚' },
    { id: 'fundamental', label: 'Fundamental', icon: '📊' },
    { id: 'valuation', label: 'Valuation', icon: '💰' },
    { id: 'technical', label: 'Technical', icon: '📈' },
    { id: 'general', label: 'General', icon: '🎯' }
  ];

  const filteredTerms = glossaryTerms.filter(term => {
    const matchesCategory = selectedCategory === 'all' || term.category === selectedCategory;
    const matchesSearch = term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         term.definition.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-3xl font-bold text-gray-900 mb-2">
          Investment Terms Glossary
        </h2>
        <p className="text-sm text-gray-600">
          Essential terminology for understanding stock research and analysis
        </p>
      </div>

      {/* Search and Filter */}
      <div className="bg-white border-2 border-gray-800 p-4">
        <div className="flex flex-col md:flex-row gap-4">
          {/* Search */}
          <div className="flex-1">
            <input
              type="text"
              placeholder="Search terms..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full px-4 py-2 border-2 border-gray-800 focus:outline-none focus:border-blue-600"
            />
          </div>

          {/* Category Filter */}
          <div className="flex gap-2 flex-wrap">
            {categories.map(cat => (
              <button
                key={cat.id}
                onClick={() => setSelectedCategory(cat.id)}
                className={`px-3 py-2 border-2 border-gray-800 font-bold text-sm transition-colors ${
                  selectedCategory === cat.id
                    ? 'bg-blue-600 text-white'
                    : 'bg-white text-gray-900 hover:bg-gray-100'
                }`}
              >
                <span className="mr-1">{cat.icon}</span>
                {cat.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Results Count */}
      <div className="text-sm text-gray-600">
        Showing {filteredTerms.length} of {glossaryTerms.length} terms
      </div>

      {/* Terms List */}
      <div className="space-y-3">
        {filteredTerms.map((term, index) => (
          <div
            key={index}
            className="bg-white border-2 border-gray-800 p-4 hover:shadow-lg transition-shadow"
          >
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <h3 className="text-lg font-bold text-gray-900 mb-2">
                  {term.term}
                </h3>
                <p className="text-sm text-gray-700 leading-relaxed">
                  {term.definition}
                </p>
              </div>
              <span className={`px-2 py-1 text-xs font-bold border-2 whitespace-nowrap ${
                term.category === 'fundamental' ? 'bg-blue-50 border-blue-600 text-blue-900' :
                term.category === 'valuation' ? 'bg-green-50 border-green-600 text-green-900' :
                term.category === 'technical' ? 'bg-purple-50 border-purple-600 text-purple-900' :
                'bg-gray-50 border-gray-600 text-gray-900'
              }`}>
                {term.category.toUpperCase()}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* No Results */}
      {filteredTerms.length === 0 && (
        <div className="bg-gray-50 border-2 border-gray-300 p-8 text-center">
          <p className="text-gray-600">
            No terms found matching your search criteria.
          </p>
        </div>
      )}

      {/* Educational Note */}
      <div className="bg-blue-50 border-2 border-blue-600 p-4">
        <h4 className="text-sm font-bold text-blue-900 mb-2">
          📚 Learning Resources
        </h4>
        <p className="text-xs text-blue-800">
          This glossary provides basic definitions for common investment terms. For deeper understanding, 
          consider consulting investment textbooks, online courses, or speaking with a financial advisor.
        </p>
      </div>
    </div>
  );
}
